name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # https://github.com/actions/setup-java/blob/main/README.md#Supported-distributions
        java-version: '14'
        java-package: jdk # optional (jdk or jre) - defaults to jdk
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.5
      with:
        cli: 1.10.3.1029 # Clojure CLI based on tools.deps
    - name: deploy to clojars
      if: success()
      env:
        CLOJARS_USERNAME: ${{ secrets.ReleaseUsername }}
        CLOJARS_PASSWORD: ${{ secrets.ReleasePassword }}
      run: |
        git config --global user.email "ci@pinkgorilla.org"
        git config --global user.name "CI/CD"
        clojure -T:build jar
        clojure -T:build deploy
